language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install: composer install --no-suggest --prefer-dist --no-interaction
script: ./vendor/bin/phpunit --debug