language: php

php:
  - '5.5'
    env: SKIP_UNIT_TEST=y
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $SKIP_UNIT_TEST = 'y' ]]; then echo "Skipping composer update..."; fi
  - if [[ $SKIP_UNIT_TEST != 'y' ]]; then composer update --no-suggest --prefer-dist --no-interaction; fi

script:
  - if [[ $SKIP_UNIT_TEST = 'y' ]]; then echo "No unit test. done"; fi
  - if [[ $SKIP_UNIT_TEST != 'y' ]]; then ./vendor/bin/phpunit --debug; fi